name: Build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'dev'

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Extract version from Dockerfile
        id: vars
        run: |
          VERSION=$(grep -E '^LABEL +version *= *"[^"]+"' Dockerfile | sed -E 's/.*version *= *"([^"]+)"/\1/')
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: prep
        uses: docker/metadata-action@v3
        with:
          images: hasecuritysolutions/logstash-oss
          tags: |
            latest
            ${{ steps.vars.outputs.version }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.prep.outputs.labels }}
